name: kogpt2-finetuning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - transformers>=4.21.0
  - datasets>=2.5.0
  - tokenizers>=0.13.0
  - accelerate>=0.12.0
  - evaluate>=0.2.0
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.64.0
  - scikit-learn>=1.1.0
  - pip
  - pip:
    - bert-score>=0.3.10
    - wandb
    - tensorboard 