name: kogpt2-finetuning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.7.0
  - torchvision=0.22.0
  - torchaudio=2.7.0
  - pytorch-cuda=12.4
  - transformers=4.46.0
  - datasets=3.1.0
  - tokenizers=0.20.3
  - huggingface_hub=0.26.2
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - tqdm=4.65.0
  - scikit-learn=1.3.0
  - pip
  - pip:
    - bert-score==0.3.13
    - peft==0.12.0
    - wandb
    - tensorboard 